In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import genfromtxt

### Создадим искусственный датасет с коррелирующими столбцами

In [2]:
size = 100
#сделаем сэмплинг данных из известных распределений
x1 = np.random.normal(0, 1, size)
x2 = np.random.gamma(2, 4, size)
x3 = []

for i in range(size):
    #сделаем искусственный столбец, коррелирующий с другим
    #часть данных зависит от первого столбца линейно, часть случайная
    res = np.random.randint(0, 10)
    if res == 0:
        x3.append(np.random.normal(0, 1, 1)[0])
    else:
        x3.append(x1[i] * 2)
x3 = np.array(x3)

x4 = []
for i in range(size):
    #аналогично для гаммы
    res = np.random.randint(0, 2)
    if res == 0:
        x4.append(np.random.gamma(2, 4, 1)[0])
    else:
        x4.append(x2[i] * 5)
x4 = np.array(x4)
x5 = np.random.randint(-10000, 10000, size) / 1000
x6 = x5 * 3

In [3]:
data = np.array([x1, x2, x3, x4, x5, x6])
data = data.transpose()
data

array([[ 2.38292863e-01,  4.13066457e+00,  4.76585726e-01,
         1.13811358e+01,  8.56100000e+00,  2.56830000e+01],
       [-1.77203079e+00,  8.77092831e+00, -3.54406157e+00,
         4.38546416e+01,  5.21000000e+00,  1.56300000e+01],
       [ 7.34126620e-01,  3.79830437e+00,  1.46825324e+00,
         1.89915218e+01, -1.00400000e+00, -3.01200000e+00],
       [-8.22901637e-01,  1.10582558e+01, -7.84455511e-01,
         5.52912792e+01, -2.73200000e+00, -8.19600000e+00],
       [ 1.16227465e+00,  3.75603729e+00,  2.32454929e+00,
         1.02711053e+01, -6.19500000e+00, -1.85850000e+01],
       [-3.26790832e-01,  1.81872352e+00, -6.53581663e-01,
         6.09356920e+00,  8.20700000e+00,  2.46210000e+01],
       [ 7.12705774e-01,  3.96267593e+00,  1.42541155e+00,
         5.93379676e+00,  2.93000000e-01,  8.79000000e-01],
       [ 1.62629464e+00,  1.27191030e+01,  3.25258929e+00,
         8.17104772e+00,  7.27400000e+00,  2.18220000e+01],
       [-1.10865747e+00,  3.25488626e+00,  8.781

### Посчитаем матрицу ковариации

In [4]:
m = []
#data2 = genfromtxt('output.csv', delimiter=',')
data2 = data.copy()

#центрируем матрицу
for i in range(6):
    m.append(data[:,i].mean())
for i in range(6):
    data2[:, i] -= m[i]
data2

array([[ 2.10433600e-01, -4.06172390e+00,  4.86890218e-01,
        -8.86076316e+00,  7.94959000e+00,  2.38487700e+01],
       [-1.79989005e+00,  5.78539847e-01, -3.53375708e+00,
         2.36127426e+01,  4.59859000e+00,  1.37957700e+01],
       [ 7.06267357e-01, -4.39408410e+00,  1.47855773e+00,
        -1.25037713e+00, -1.61541000e+00, -4.84623000e+00],
       [-8.50760901e-01,  2.86586737e+00, -7.74151020e-01,
         3.50493802e+01, -3.34341000e+00, -1.00302300e+01],
       [ 1.13441538e+00, -4.43635118e+00,  2.33485378e+00,
        -9.97079367e+00, -6.80641000e+00, -2.04192300e+01],
       [-3.54650095e-01, -6.37366495e+00, -6.43277172e-01,
        -1.41483298e+01,  7.59559000e+00,  2.27867700e+01],
       [ 6.84846510e-01, -4.22971254e+00,  1.43571604e+00,
        -1.43081022e+01, -3.18410000e-01, -9.55230000e-01],
       [ 1.59843538e+00,  4.52671458e+00,  3.26289378e+00,
        -1.20708513e+01,  6.66259000e+00,  1.99877700e+01],
       [-1.13651673e+00, -4.93750221e+00,  8.884

In [5]:
cov = np.dot(data2.transpose(), data2)
cov = cov / (size - 1)
cov

array([[ 1.11328121e+00,  3.25380446e-01,  2.02770315e+00,
         3.54621946e+00, -1.40433440e-01, -4.21300321e-01],
       [ 3.25380446e-01,  3.18528275e+01,  6.27009519e-01,
         4.36168150e+01, -4.71056055e+00, -1.41316817e+01],
       [ 2.02770315e+00,  6.27009519e-01,  4.20158395e+00,
         6.95782833e+00, -5.49640464e-01, -1.64892139e+00],
       [ 3.54621946e+00,  4.36168150e+01,  6.95782833e+00,
         4.95749945e+02, -1.75273324e+01, -5.25819971e+01],
       [-1.40433440e-01, -4.71056055e+00, -5.49640464e-01,
        -1.75273324e+01,  3.54497411e+01,  1.06349223e+02],
       [-4.21300321e-01, -1.41316817e+01, -1.64892139e+00,
        -5.25819971e+01,  1.06349223e+02,  3.19047670e+02]])

### Сингулярное разложение


In [51]:
import math
class SVD():

    def __init__(self, matrix):
        self.matrix = matrix
        self.size = min(matrix.shape[0], matrix.shape[1])
        self.V = np.eye(self.size)

    # Точность
    def ND(self,A):
        res = 0
        for i in range(1,self.size):
            for k in range(i):
                res += A[i,k]**2
        return math.sqrt(res)

    # Матрица Гивенса
    def G(self,j,k,c,s):
        a = np.eye(self.size)
        a[j,j] = c #math.cos(theta)
        a[k,j] = s #math.sin(theta)
        a[j,k] = -s #-math.sin(theta)
        a[k,k] = c #math.cos(theta)
        return a

    def Gt(self,j,k,c,s):
        a = np.eye(self.size)
        a[j,j] = c #math.cos(theta)
        a[j,k] = s #math.sin(theta)
        a[k,j] = -s #-math.sin(theta)
        a[k,k] = c #math.cos(theta)
        return a

    def sign(self, x):
        if x >= 0:
            return 1
        else:
            return -1

    # Метод Якоби вычисления сч и св для симметрической матрицы
    def Jakobi(self,A):
        lenght = A.shape[0]
        for i in range(1,lenght):
            for k in range(i):
                if abs(A[i,k]) > 10**(-8):
                    tau = (A[i,i] - A[k,k])/(2*A[i,k])
                    if abs(tau) < 10**(-14):
                        theta = math.pi/4
                        c = math.cos(theta)
                        s = math.sin(theta)
                    else:
                        t = 1/(tau + self.sign(tau)*math.sqrt(tau**2 + 1))
                        c = 1/math.sqrt(t**2 + 1)
                        s = t*c
                    A = np.dot(self.Gt(i, k, c, s), A)
                    A = np.dot(A, self.G(i, k, c, s))
                    self.V = np.dot(self.V, self.G(i,k,c,s))
        return A

    # Возвращает список сингулярных чисел и ортогональную матрицу правых собственных векторов
    def pca(self,epsilon):
        B = np.dot(self.matrix.transpose(), self.matrix)
        B = B / (max(self.matrix.shape[0], self.matrix.shape[1]) - 1)
        while self.ND(B) > epsilon:
            B = self.Jakobi(B)

        sing_val = []
        for i in range(B.shape[0]):
            sing_val.append(math.sqrt(abs(B[i,i])))
        return sing_val, self.V


In [52]:
H = data2.copy()

svd = SVD(H)
eps = 10**(-8)
singular, V = svd.pca(eps)
singular

[0.32903235006983506,
 5.243519154650291,
 2.2538081467202975,
 22.790005246776506,
 1.1518094297755837e-07,
 18.31251765051295]

In [66]:
# Посчитаем вклад каждой компоненты
components = []
s = 0
for i in singular:
    s += i
for i in singular:
    components.append(i / s)
components

[0.006724705984600873,
 0.10716613315426939,
 0.04606293918873138,
 0.465778166309652,
 2.3540480940210397e-09,
 0.3742680530086982]

In [68]:
P = []
T = []
for i in range(len(singular)):
    # Будем рассматривать компоненты, вклад которых выше 30 процентов
    if components[i] > 0.3:
        P.append(singular[i])
        T.append(V[:,i]) # Матрица преобразований

In [76]:
P = np.array([[P[0], 0], [0, P[1]]])
T = np.array(T)

C:\Users\User\AppData\Local\Temp\ipykernel_16436\1884738543.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  P = np.array([[P[0], 0], [0, P[1]]])


In [77]:
T

array([[ 6.83015686e-03,  9.41289379e-02,  1.39452230e-02,
         9.40906307e-01, -1.02758914e-01, -3.08276742e-01],
       [ 2.21877253e-03,  5.14048316e-04,  1.91031728e-03,
         3.26354070e-01,  2.98912058e-01,  8.96736174e-01]])